### ISSUE TITLE
Consider using normalized form of the project's version

### ISSUE THREAD

**Issue by piotr-dobrogost** [fanstatic/js.deform#12]
As per https://mail.python.org/pipermail/distutils-sig/2015-August/026729.html please consider using normalized form (according to PEP 440) of the project's version. This would be 2.0a2.post3 instead of 2.0a2-3

The same problem is with js.jqueryui-tagit and js.html5shiv packages although the latter one seems to be hosted on bitbucket (https://bitbucket.org/fanstatic/js.html5shiv) as opposed to the rest of js.\* packages.

**Comment by janjaapdriessen** [comment]
Thanks @piotr-dobrogost we should definitely do this. Are you willing to be a maintainer on github/bitbucket/pypi to do the legwork? If so, please tell me your pypi username. If not, I can do it. Are js.deform, js.jqueryui-tagit, js.html5shiv the only packages to which this applies?

**Comment by piotr-dobrogost** [comment]
If you could do it that would be great. I believe I listed all effected packages.

**Comment by janjaapdriessen** [comment]
Apologies for the delay; I updated: https://pypi.python.org/pypi/js.html5shiv/3.7.3

@disko could you pick up js.jqueryui_tagit and js.deform ? I am not a maintainer on pypi.

**Comment by disko** [comment]
I'm very short on time right now.  I'll try to get it done by the end of the week.

@janjaapdriessen: I added you as a maintainer for all ``js.*`` packages oy PyPI that I'm owner of.

**Comment by disko** [comment]
Done.
